const MOCK = {
  'item': {
    'name': 'index.xml',
    'internalName': 'Home',
    'contentType': '/page/entry',
    'uri': '/site/website/index.xml',
    'path': '/site/website',
    'browserUri': '',
    'site': 'launcher',
    'lockOwner': '',
    'user': '',
    'userFirstName': '',
    'userLastName': '',
    'nodeRef': null,
    'metaDescription': null,
    'eventDate': null,
    'endpoint': null,
    'timezone': null,
    'numOfChildren': 4,
    'scheduledDate': null,
    'publishedDate': null,
    'mandatoryParent': null,
    'categoryRoot': null,
    'lastEditDate': null,
    'form': '/page/entry',
    'formPagePath': 'simple',
    'renderingTemplates': [{'uri': '/templates/web/entry.ftl', 'name': 'DEFAULT'}],
    'submissionComment': null,
    'components': null,
    'documents': null,
    'levelDescriptors': null,
    'pages': null,
    'parentPath': null,
    'orders': [{'name': null, 'id': 'default', 'order': -1.0, 'disabled': null, 'placeInNav': null}],
    'children': [
      {
        'name': 'crafter-level-descriptor.level.xml',
        'internalName': '',
        'contentType': '/component/level-descriptor',
        'uri': '/site/website/crafter-level-descriptor.level.xml',
        'path': '/site/website',
        'browserUri': '/crafter-level-descriptor.level.xml',
        'navigation': false,
        'floating': true,
        'hideInAuthoring': false,
        'previewable': false,
        'lockOwner': '',
        'user': '',
        'userFirstName': '',
        'userLastName': '',
        'nodeRef': null,
        'metaDescription': null,
        'site': 'launcher',
        'page': true,
        'component': true,
        'document': false,
        'asset': false,
        'isContainer': false,
        'container': false,
        'disabled': false,
        'savedAsDraft': false,
        'submitted': false,
        'submittedForDeletion': false,
        'scheduled': false,
        'published': false,
        'deleted': false,
        'inProgress': false,
        'live': true,
        'inFlight': false,
        'isDisabled': false,
        'isSavedAsDraft': false,
        'isInProgress': false,
        'isLive': true,
        'isSubmittedForDeletion': false,
        'isScheduled': false,
        'isPublished': false,
        'isNavigation': false,
        'isDeleted': false,
        'isNew': false,
        'isSubmitted': false,
        'isFloating': false,
        'isPage': true,
        'isPreviewable': false,
        'isComponent': true,
        'isDocument': false,
        'isAsset': false,
        'isInFlight': false,
        'eventDate': null,
        'endpoint': null,
        'timezone': null,
        'numOfChildren': 0,
        'scheduledDate': null,
        'publishedDate': null,
        'mandatoryParent': null,
        'isLevelDescriptor': true,
        'categoryRoot': null,
        'lastEditDate': null,
        'form': '/component/level-descriptor',
        'formPagePath': 'simple',
        'renderingTemplates': [{'uri': '', 'name': 'DEFAULT'}],
        'folder': false,
        'submissionComment': null,
        'components': null,
        'documents': null,
        'levelDescriptors': null,
        'pages': null,
        'parentPath': null,
        'orders': [],
        'children': [],
        'size': 0.0,
        'sizeUnit': null,
        'mimeType': 'application/xml',
        'newFile': false,
        'new': false,
        'reference': false,
        'levelDescriptor': true
      },
      {
        'name': 'crafter-component.xml',
        'internalName': '',
        'contentType': '',
        'uri': '/site/website/crafter-component.xml',
        'path': '/site/website',
        'browserUri': '/crafter-component.xml',
        'navigation': false,
        'floating': true,
        'hideInAuthoring': true,
        'previewable': true,
        'lockOwner': '',
        'user': '',
        'userFirstName': '',
        'userLastName': '',
        'nodeRef': null,
        'metaDescription': null,
        'site': 'launcher',
        'page': true,
        'component': false,
        'document': false,
        'asset': false,
        'isContainer': false,
        'container': false,
        'disabled': false,
        'savedAsDraft': false,
        'submitted': false,
        'submittedForDeletion': false,
        'scheduled': false,
        'published': false,
        'deleted': false,
        'inProgress': false,
        'live': true,
        'inFlight': false,
        'isDisabled': false,
        'isSavedAsDraft': false,
        'isInProgress': false,
        'isLive': true,
        'isSubmittedForDeletion': false,
        'isScheduled': false,
        'isPublished': false,
        'isNavigation': false,
        'isDeleted': false,
        'isNew': false,
        'isSubmitted': false,
        'isFloating': false,
        'isPage': true,
        'isPreviewable': true,
        'isComponent': false,
        'isDocument': false,
        'isAsset': false,
        'isInFlight': false,
        'eventDate': null,
        'endpoint': null,
        'timezone': null,
        'numOfChildren': 0,
        'scheduledDate': null,
        'publishedDate': null,
        'mandatoryParent': null,
        'isLevelDescriptor': false,
        'categoryRoot': null,
        'lastEditDate': null,
        'form': null,
        'formPagePath': null,
        'renderingTemplates': [{'uri': '/templates/system/common/component.ftl', 'name': 'DEFAULT'}],
        'folder': false,
        'submissionComment': null,
        'components': null,
        'documents': null,
        'levelDescriptors': null,
        'pages': null,
        'parentPath': null,
        'orders': [],
        'children': [],
        'size': 0.0,
        'sizeUnit': null,
        'mimeType': 'application/xml',
        'newFile': false,
        'new': false,
        'reference': false,
        'levelDescriptor': false
      },
      {
        'name': 'index.xml',
        'internalName': 'Entertainment',
        'contentType': '/page/entertainment',
        'uri': '/site/website/movies/index.xml',
        'path': '/site/website/movies',
        'browserUri': '/movies',
        'navigation': false,
        'floating': true,
        'hideInAuthoring': false,
        'previewable': true,
        'lockOwner': '',
        'user': 'admin',
        'userFirstName': 'admin',
        'userLastName': '',
        'nodeRef': null,
        'metaDescription': null,
        'site': 'launcher',
        'page': true,
        'component': false,
        'document': false,
        'asset': false,
        'isContainer': true,
        'container': true,
        'disabled': false,
        'savedAsDraft': false,
        'submitted': false,
        'submittedForDeletion': false,
        'scheduled': false,
        'published': false,
        'deleted': false,
        'inProgress': true,
        'live': false,
        'inFlight': false,
        'isDisabled': false,
        'isSavedAsDraft': false,
        'isInProgress': true,
        'isLive': false,
        'isSubmittedForDeletion': false,
        'isScheduled': false,
        'isPublished': false,
        'isNavigation': false,
        'isDeleted': false,
        'isNew': true,
        'isSubmitted': false,
        'isFloating': false,
        'isPage': true,
        'isPreviewable': true,
        'isComponent': false,
        'isDocument': false,
        'isAsset': false,
        'isInFlight': false,
        'eventDate': '2017-10-31T12:54:33Z',
        'endpoint': null,
        'timezone': null,
        'numOfChildren': 0,
        'scheduledDate': null,
        'publishedDate': null,
        'mandatoryParent': null,
        'isLevelDescriptor': false,
        'categoryRoot': null,
        'lastEditDate': '2017-10-31T12:54:33Z',
        'form': '/page/entertainment',
        'formPagePath': 'simple',
        'renderingTemplates': [{'uri': '/templates/web/entertainment.ftl', 'name': 'DEFAULT'}],
        'folder': false,
        'submissionComment': null,
        'components': null,
        'documents': null,
        'levelDescriptors': null,
        'pages': null,
        'parentPath': null,
        'orders': [{'name': null, 'id': 'default', 'order': -1.0, 'disabled': null, 'placeInNav': null}],
        'children': [],
        'size': 0.0,
        'sizeUnit': null,
        'mimeType': 'application/xml',
        'newFile': false,
        'new': true,
        'reference': false,
        'levelDescriptor': false
      },
      {
        'name': 'index.xml',
        'internalName': 'Player',
        'contentType': '/page/player',
        'uri': '/site/website/player/index.xml',
        'path': '/site/website/player',
        'browserUri': '/player',
        'navigation': false,
        'floating': true,
        'hideInAuthoring': false,
        'previewable': true,
        'lockOwner': '',
        'user': 'admin',
        'userFirstName': 'admin',
        'userLastName': '',
        'nodeRef': null,
        'metaDescription': null,
        'site': 'launcher',
        'page': true,
        'component': false,
        'document': false,
        'asset': false,
        'isContainer': true,
        'container': true,
        'disabled': false,
        'savedAsDraft': false,
        'submitted': false,
        'submittedForDeletion': false,
        'scheduled': false,
        'published': false,
        'deleted': false,
        'inProgress': true,
        'live': false,
        'inFlight': false,
        'isDisabled': false,
        'isSavedAsDraft': false,
        'isInProgress': true,
        'isLive': false,
        'isSubmittedForDeletion': false,
        'isScheduled': false,
        'isPublished': false,
        'isNavigation': false,
        'isDeleted': false,
        'isNew': true,
        'isSubmitted': false,
        'isFloating': false,
        'isPage': true,
        'isPreviewable': true,
        'isComponent': false,
        'isDocument': false,
        'isAsset': false,
        'isInFlight': false,
        'eventDate': '2017-10-31T12:54:55Z',
        'endpoint': null,
        'timezone': null,
        'numOfChildren': 0,
        'scheduledDate': null,
        'publishedDate': null,
        'mandatoryParent': null,
        'isLevelDescriptor': false,
        'categoryRoot': null,
        'lastEditDate': '2017-10-31T12:54:55Z',
        'form': '/page/player',
        'formPagePath': 'simple',
        'renderingTemplates': [{'uri': '/templates/web/player.ftl', 'name': 'DEFAULT'}],
        'folder': false,
        'submissionComment': null,
        'components': null,
        'documents': null,
        'levelDescriptors': null,
        'pages': null,
        'parentPath': null,
        'orders': [{'name': null, 'id': 'default', 'order': -1.0, 'disabled': null, 'placeInNav': null}],
        'children': [],
        'size': 0.0,
        'sizeUnit': null,
        'mimeType': 'application/xml',
        'newFile': false,
        'new': true,
        'reference': false,
        'levelDescriptor': false
      }
    ],
    'size': 0.0,
    'sizeUnit': null,
    'mimeType': 'application/xml',
    'navigation': false,
    'floating': true,
    'hideInAuthoring': false,
    'previewable': true,
    'page': true,
    'component': false,
    'document': false,
    'asset': false,
    'isContainer': true,
    'container': true,
    'disabled': false,
    'savedAsDraft': false,
    'submitted': false,
    'submittedForDeletion': false,
    'scheduled': false,
    'published': false,
    'deleted': false,
    'inProgress': false,
    'live': true,
    'inFlight': false,
    'isDisabled': false,
    'isSavedAsDraft': false,
    'isInProgress': false,
    'isLive': true,
    'isSubmittedForDeletion': false,
    'isScheduled': false,
    'isPublished': false,
    'isNavigation': false,
    'isDeleted': false,
    'isNew': false,
    'isSubmitted': false,
    'isFloating': false,
    'isPage': true,
    'isPreviewable': true,
    'isComponent': false,
    'isDocument': false,
    'isAsset': false,
    'isInFlight': false,
    'isLevelDescriptor': false,
    'folder': false,
    'newFile': false,
    'new': false,
    'reference': false,
    'levelDescriptor': false
  }
};

interface ContentItemFlags {
  levelDescriptor;
  reference;
}

interface RenderingTemplate {
  name: 'DEFAULT' | 'MOBILE';
  internalURI: string;
}

export class ContentItem {
  label: string;
  browserURL: string;
  internalURL: string;
  siteCode: string;
  formURI: string;
  renderingTemplates: RenderingTemplate[];
  children: ContentItem[];
  numOfChildren: number;
  is: ContentItemFlags;

  static fromJSON(json) {
    let item = new ContentItem();
    // item. = json.;

    item.label = json.internalName || json.name;
    item.browserURL = json.browserUri;
    item.siteCode = json.site;
    item.internalURL = json.uri;
    item.children = (json.children && json.children.length)
      ? json.children.map((itemJSON) => ContentItem.fromJSON(itemJSON))
      : null;
    item.numOfChildren = json.numOfChildren;
    item.formURI = json.form;
    item.renderingTemplates = json.renderingTemplates;
    // item.internalURN: string = json.path;

    return item;
  }
}
