
export enum StoreActionsEnum {

  // selectedItems
  SELECT_ITEM = 'SELECT_ITEM',
  DESELECT_ITEM = 'DESELECT_ITEM',
  DESELECT_ITEMS = 'DESELECT_ITEMS',
  SELECT_ITEMS = 'SELECT_ITEMS',

  // expandedPanels
  EXPAND_PANEL = 'EXPAND_PANEL',
  COLLAPSE_PANEL = 'COLLAPSE_PANEL',
  EXPAND_PANELS = 'EXPAND_PANELS',
  COLLAPSE_PANELS = 'COLLAPSE_PANELS'

}
