
export enum StoreActionsEnum {

  REDUX_INIT = '@@INIT',
  STUDIO_INIT = '@@studio/INIT',

  // selectedItems
  SELECT_ITEM = 'SELECT_ITEM',
  DESELECT_ITEM = 'DESELECT_ITEM',
  DESELECT_ITEMS = 'DESELECT_ITEMS',
  SELECT_ITEMS = 'SELECT_ITEMS',

  // expandedPanels
  EXPAND_PANEL = 'EXPAND_PANEL',
  COLLAPSE_PANEL = 'COLLAPSE_PANEL',
  EXPAND_PANELS = 'EXPAND_PANELS',
  COLLAPSE_PANELS = 'COLLAPSE_PANELS',

  // expandedPaths
  EXPAND_PATH = 'EXPAND_PATH',
  COLLAPSE_PATH = 'COLLAPSE_PATH',
  EXPAND_PATHS = 'EXPAND_PATHS',
  COLLAPSE_PATHS = 'COLLAPSE_PATHS',

  // previewTabs
  OPEN_TAB = 'OPEN_TAB',
  CLOSE_TAB = 'CLOSE_TAB',
  SELECT_TAB = 'SELECT_TAB',
  GUEST_CHECK_IN = 'GUEST_CHECK_IN',
  NAVIGATE_ON_ACTIVE = 'NAVIGATE_ON_ACTIVE',
  OPEN_TAB_BACKGROUND = 'OPEN_TAB_BACKGROUND',
  TAB_NAVIGATE_BACK = 'TAB_NAVIGATE_BACK',
  TAB_NAVIGATE_FORWARD = 'TAB_NAVIGATE_FORWARD',

  // projects
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  FETCH_PROJECT = 'FETCH_PROJECT',
  PROJECTS_FETCHED = 'PROJECTS_FETCHED',
  PROJECT_FETCHED = 'PROJECT_FETCHED',
  PROJECTS_FETCH_ERROR = 'PROJECTS_FETCH_ERROR',
  PROJECT_FETCH_ERROR = 'PROJECT_FETCH_ERROR',
  CREATE_PROJECT = 'CREATE_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  EDIT_PROJECT = 'EDIT_PROJECT',

  SELECT_PROJECT = 'SELECT_PROJECT',
  DESELECT_PROJECT = 'DESELECT_PROJECT',

  // assets
  FETCH_ASSETS = 'FETCH_ASSETS',
  FETCH_ASSET = 'FETCH_ASSET',
  ASSETS_FETCHED = 'ASSETS_FETCHED',
  SOME_ASSETS_FETCHED = 'SOME_ASSETS_FETCHED',
  ASSET_FETCHED = 'ASSET_FETCHED',
  ASSETS_FETCH_ERROR = 'ASSETS_FETCH_ERROR',
  ASSET_FETCH_ERROR = 'ASSET_FETCH_ERROR',
  CREATE_ASSET = 'CREATE_ASSET',
  UPDATE_ASSET = 'UPDATE_ASSET',
  DELETE_ASSET = 'DELETE_ASSET',
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  ASSET_DELETED = 'ASSET_DELETED',
  EDIT_ASSET = 'EDIT_ASSET',


}
