
export enum StoreActionsEnum {

  REDUX_INIT = '@@INIT',
  STUDIO_INIT = '@@studio/INIT',

  // selectedItems
  SELECT_ITEM = 'SELECT_ITEM',
  DESELECT_ITEM = 'DESELECT_ITEM',
  DESELECT_ITEMS = 'DESELECT_ITEMS',
  SELECT_ITEMS = 'SELECT_ITEMS',

  // expandedPanels
  EXPAND_PANEL = 'EXPAND_PANEL',
  COLLAPSE_PANEL = 'COLLAPSE_PANEL',
  EXPAND_PANELS = 'EXPAND_PANELS',
  COLLAPSE_PANELS = 'COLLAPSE_PANELS',

  // expandedPaths
  EXPAND_PATH = 'EXPAND_PATH',
  COLLAPSE_PATH = 'COLLAPSE_PATH',
  EXPAND_PATHS = 'EXPAND_PATHS',
  COLLAPSE_PATHS = 'COLLAPSE_PATHS',

  // previewTabs
  OPEN_TAB = 'OPEN_TAB',
  CLOSE_TAB = 'CLOSE_TAB',
  SELECT_TAB = 'SELECT_TAB',
  GUEST_CHECK_IN = 'GUEST_CHECK_IN',
  NAVIGATE_ON_ACTIVE = 'NAVIGATE_ON_ACTIVE',
  OPEN_TAB_BACKGROUND = 'OPEN_TAB_BACKGROUND',
  TAB_NAVIGATE_BACK = 'TAB_NAVIGATE_BACK',
  TAB_NAVIGATE_FORWARD = 'TAB_NAVIGATE_FORWARD',

  // sites
  FETCH_SITES = 'FETCH_SITES',
  FETCH_SITE = 'FETCH_SITE',
  SITES_FETCHED = 'SITES_FETCHED',
  SITE_FETCHED = 'SITE_FETCHED',
  SITES_FETCH_ERROR = 'SITES_FETCH_ERROR',
  SITE_FETCH_ERROR = 'SITE_FETCH_ERROR',
  CREATE_SITE = 'CREATE_SITE',
  UPDATE_SITE = 'UPDATE_SITE',
  DELETE_SITE = 'DELETE_SITE',
  SITE_CREATED = 'SITE_CREATED',
  SITE_UPDATED = 'SITE_UPDATED',
  SITE_DELETED = 'SITE_DELETED',
  EDIT_SITE = 'EDIT_SITE',

  SELECT_SITE = 'SELECT_SITE',
  DESELECT_SITE = 'DESELECT_SITE',

  // assets
  FETCH_ASSETS = 'FETCH_ASSETS',
  FETCH_ASSET = 'FETCH_ASSET',
  ASSETS_FETCHED = 'ASSETS_FETCHED',
  SOME_ASSETS_FETCHED = 'SOME_ASSETS_FETCHED',
  ASSET_FETCHED = 'ASSET_FETCHED',
  ASSETS_FETCH_ERROR = 'ASSETS_FETCH_ERROR',
  ASSET_FETCH_ERROR = 'ASSET_FETCH_ERROR',
  CREATE_ASSET = 'CREATE_ASSET',
  UPDATE_ASSET = 'UPDATE_ASSET',
  DELETE_ASSET = 'DELETE_ASSET',
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  ASSET_DELETED = 'ASSET_DELETED',
  EDIT_ASSET = 'EDIT_ASSET',


}
