
export enum WindowMessageTopicEnum {

  ALL = 'ALL',

  GUEST_CHECK_IN = 'GUEST_CHECK_IN',
  GUEST_LOAD_EVENT = 'GUEST_LOAD_EVENT',

  HOST_ICE_START_REQUEST = 'HOST_ICE_START_REQUEST',
  HOST_END_ICE_REQUEST = 'HOST_END_ICE_REQUEST',
  HOST_RELOAD_REQUEST = 'HOST_RELOAD_REQUEST',
  HOST_NAV_REQUEST = 'HOST_NAV_REQUEST',

  NAV_REQUEST = 'NAV_REQUEST',

  SITE_CREATED = 'SITE_CREATED',
  SITE_UPDATED = 'SITE_UPDATED',
  SITE_DELETED = 'SITE_DELETED'

}
